export const GET_PLANES_TRAINS_CARS = "GET_PLANES_TRAINS_CARS";
export const GET_PLANES_TRAINS_CARS_SUCCESS = "GET_PLANES_TRAINS_CARS_SUCCESS";
export const GET_PLANES_TRAINS_CARS_FAIL = "GET_PLANES_TRAINS_CARS_FAIL";
export const CHANGE_FILTER_PLANES_TRAINS_CARS_VALUE =
  "CHANGE_FILTER_PLANES_TRAINS_CARS_VALUE";
export const CLEAR_FILTERS_PLANES_TRAINS_CARS =
  "CLEAR_FILTERS_PLANES_TRAINS_CARS";
export const CLEAR_FILTER_PLANES_TRAINS_CARS_BY_NAME =
  "CLEAR_FILTER_PLANES_TRAINS_CARS_BY_NAME";
